
##### Copyright (c) DeepSphere.AI 2021
##### All rights reserved

###### We are sharing this partial code for learning and research, and the idea behind us sharing the source code is to stimulate ideas and thoughts for the learners .

###### Author: # DeepSphere.AI | deepsphere.ai | dsschoolofai.com info@deepsphere.ai

###### Release: Initial release



## Filtering


In [11]:
from scipy import signal
import numpy as np
x = np.arange(15).reshape(3, 5)
domain = np.identity(3)
print("Input: " )
print(x)
print("Signal: ")
print(signal.order_filter(x, domain, 1))

Input: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Signal: 
[[0. 1. 2. 3. 0.]
 [5. 6. 7. 8. 3.]
 [0. 5. 6. 7. 8.]]
