
##### Copyright (c) DeepSphere.AI 2021
##### All rights reserved

###### We are sharing this partial code for learning and research, and the idea behind us sharing the source code is to stimulate ideas and thoughts for the learners .

###### Author: # DeepSphere.AI | deepsphere.ai | dsschoolofai.com info@deepsphere.ai

###### Release: Initial release



## Finding Inverse

In [4]:
import numpy as np
from scipy import linalg
A = np.array([[1,2,3],[4,5,6],[2,3,8]])
print(A)
print(linalg.inv(A))

[[1 2 3]
 [4 5 6]
 [2 3 8]]
[[-1.83333333  0.58333333  0.25      ]
 [ 1.66666667 -0.16666667 -0.5       ]
 [-0.16666667 -0.08333333  0.25      ]]
